### ISSUE TITLE
migrate build to use gcc / eclipse instead of keil

### ISSUE THREAD

**Issue by usaguerrilla** [far-far-away-science/hab#42]
I added wiki just need to move code to use it

**Comment by usaguerrilla** [comment]
might be a good idea to leave keil compiling (use trig functions there) as I can debug reliably only from it for now.
need to investigate further.

**Comment by stcarlso** [comment]
Is this for Tiva or STM32 builds?

**Comment by usaguerrilla** [comment]
Tiva

Sent from my Windows Phone
________________________________

**Comment by stcarlso** [comment]
This is probably not worth it for the Tiva builds unless you plan on updating the V1 Telemetry board after the first flight, or if you plan on maintaining a way to build the older code against an open source toolchain. Will leave the issue open until fixed for STM32 builds.

**Comment by Scorillo47** [comment]
It's fine if we use Keil for the TIVA. I was using Code Composer, BTW, so far

GCC/Eclipse is a good common platform when we move to STM32

**Comment by usaguerrilla** [comment]
You might be right. Might be a bad idea to change stuff which we know works fine.

**Comment by usaguerrilla** [comment]
will do in v2
