### ISSUE TITLE
Add sin/cos/asin tables instead of using trig functions

### ISSUE THREAD

**Issue by usaguerrilla** [far-far-away-science/hab#43]
(need to migrate to gcc / eclipse 1st)

**Comment by Scorillo47** [comment]
Where are we using sin/cos/asin in our code?

**Comment by stcarlso** [comment]
This is being used in the APRS sine generation section. There is a method which does not involve the use of these functions which we can try.

**Comment by usaguerrilla** [comment]
Any method will do but error compared to reference solution (trig) should be very small. Especially when frequency changed from 1200 to 2200 and back.

Sent from my Windows Phone
________________________________

**Comment by usaguerrilla** [comment]
no longer needed
