### ISSUE TITLE
Helium cylinders support structure for Adi's car

### ISSUE THREAD

**Issue by usaguerrilla** [far-far-away-science/hab#49]

**Comment by stcarlso** [comment]
How big does it need to be? Can this be made out of acrylic or wood on the laser?

**Comment by usaguerrilla** [comment]
Adi has all the specs he measured them. I think it needs to be made from sturdy wood beams as cylinders are heavy. If you want you can chat to Adi and take this task from him.

**Comment by Scorillo47** [comment]
I can make this easily at home - have all the materials.

**Comment by usaguerrilla** [comment]
make sure you can do all items as you have many. if Stephen can help it would be awesome.

**Comment by usaguerrilla** [comment]
Actually it can be done using laser cutter. Just need quite a bit of plywood. Basically mesh of plywood to support cylinders.

**Comment by Scorillo47** [comment]
No. It can't be done with laser cutter. These are large 2x4s

**Comment by Scorillo47** [comment]
Important - this task is very specific to my car and the props can't be reused except for a van of the same make/model (Honda Odyssey 2014) 

For a different car please open a separate task

**Comment by usaguerrilla** [comment]
Depends on material. Plywood can be laser cut and assembled into a case. Need to research universal transporting solutions. Welders dont custom build this for each car.

**Comment by Scorillo47** [comment]
It's totally OK from plywood it's just that it is more work. 
Adi

Date: Thu, 3 Mar 2016 13:58:22 -0800

**Comment by Scorillo47** [comment]
Done!
