### ISSUE TITLE
Test final assembly including radio (as we have new antenna)

### ISSUE THREAD

**Issue by usaguerrilla** [far-far-away-science/hab#57]

**Comment by Scorillo47** [comment]
Need to think more about this. In the past antenna testing took a lot of time and was unclear what the success criteria was.

**Comment by usaguerrilla** [comment]
We need to test if it works at all 1st. Then we can think about what to do next.

I will add a meeting for Thursday.

Test plan:
- test with SDR directional antenna to make sure signal can be received
- test with SDR omnidirectional large antenna to make sure signal can be received
- test with Kenwood directional antenna to make sure signal can be received
- test with Kenwood omnidirectional large antenna to make sure signal can be received

Send from City Center
Receive at Issaquah highlands

**Comment by usaguerrilla** [comment]
done
